import customtkinter as ctk
import os
import random

# Main tab variables
output_mode_var = ctk.StringVar(value="gif")
output_folder = os.path.join(os.path.dirname(os.path.abspath(__file__)), "output")
prefix_var = ctk.StringVar(value="washer")
# Initialize with default values to prevent empty string errors
fps_var = ctk.IntVar()
fps_var.set(10)
quality_var = ctk.IntVar()
quality_var.set(75)
codec_var = ctk.StringVar()
codec_var.set("libx264")
bitrate_var = ctk.IntVar()
bitrate_var.set(2000)
output_fps_var = ctk.StringVar()
output_fps_var.set("Original FPS")
start_time_var = ctk.DoubleVar()
start_time_var.set(0.0)
end_time_var = ctk.DoubleVar()
end_time_var.set(5.0)
duration_var = ctk.DoubleVar()
duration_var.set(5.0)
copies_var = ctk.IntVar()
copies_var.set(1)
speed_var = ctk.StringVar(value="1.0x")
effects_status_var = ctk.StringVar(value="No effects applied")

# Effects tab variables
consistent_effects = ctk.BooleanVar(value=False)
effect_seed = ctk.StringVar(value="1")
brightness_enabled = ctk.BooleanVar(value=False)
brightness_min_var = ctk.DoubleVar(value=1.0)
brightness_max_var = ctk.DoubleVar(value=1.0)
contrast_enabled = ctk.BooleanVar(value=False)
contrast_min_var = ctk.DoubleVar(value=1.0)
contrast_max_var = ctk.DoubleVar(value=1.0)
saturation_enabled = ctk.BooleanVar(value=False)
saturation_min_var = ctk.DoubleVar(value=1.0)
saturation_max_var = ctk.DoubleVar(value=1.0)
hue_enabled = ctk.BooleanVar(value=False)
hue_min_var = ctk.DoubleVar(value=0.0)
hue_max_var = ctk.DoubleVar(value=0.0)
blur_enabled = ctk.BooleanVar(value=False)
blur_radius_var = ctk.DoubleVar(value=5.0)
rotation_enabled = ctk.BooleanVar(value=False)
rotation_angle_var = ctk.DoubleVar(value=0.0)
resize_enabled = ctk.BooleanVar(value=False)
resize_width_var = ctk.IntVar(value=800)
resize_height_var = ctk.IntVar(value=600)
noise_enabled = ctk.BooleanVar(value=False)
noise_level_var = ctk.DoubleVar(value=0.5)
region_enabled = ctk.BooleanVar(value=False)
region_x_var = ctk.IntVar(value=0)
region_y_var = ctk.IntVar(value=0)
region_width_var = ctk.IntVar(value=100)
region_height_var = ctk.IntVar(value=100)
bitplane_enabled = ctk.BooleanVar(value=False)
bitplane_intensity_var = ctk.DoubleVar(value=0.5)
bitplane_planes_var = ctk.IntVar(value=1)
overlay_enabled = ctk.BooleanVar(value=False)
frame_overlay_interval = ctk.IntVar(value=1)
shadow_enabled = ctk.BooleanVar(value=False)
shadow_h_lines_var = ctk.IntVar(value=0)
shadow_v_lines_var = ctk.IntVar(value=0)
shadow_intensity_var = ctk.DoubleVar(value=0.1)
shadow_line_width_var = ctk.IntVar(value=1)
shadow_speed_var = ctk.DoubleVar(value=0.5)
