name: Build Mac App

on:
  push:
    branches: [ main, mac-build ]
  release:
    types: [published]

jobs:
  build-mac:
    runs-on: macos-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
    
    - name: Install FFmpeg
      run: brew install ffmpeg
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install customtkinter==5.2.0
        pip install -r requirements.txt
        pip install --upgrade pyinstaller
    
    - name: Build app
      run: |
        python -m PyInstaller --clean --noconfirm content-spoofer-mac-fixed.spec
    
    - name: Package app
      run: |
        cd dist
        tar -czf ReelsWasher-Mac.tar.gz ReelsWasher/
    
    - name: Upload build artifact
      uses: actions/upload-artifact@v3
      with:
        name: ReelsWasher-Mac
        path: dist/ReelsWasher-Mac.tar.gz

